### ISSUE TITLE
Can't compare Time Published and Start Time

### ISSUE THREAD

**Issue by nate-chambers** [jamespeccia/YouTubeFirstCommentBot#1]
I am very new to coding, and just trying to work each error at a time.
First error was when importing `from apiclient.discovery import build`
I looked online and found that `from googleapiclient.discovery import build` is what I should be using instead. Not sure if this works with your project but it led me to the next error.

It opened up google and signed in, then quit because I did't set up the directory right for windows.

Now I'm getting this error 
`Traceback (most recent call last):
  File "C:/Users/natea/Desktop/YouTubeFirstCommentBot-master/run.py", line 40, in <module>
    main()
  File "C:/Users/natea/Desktop/YouTubeFirstCommentBot-master/run.py", line 20, in main
    upload = youtube.get_latest_upload(channel, start_time)
  File "C:\Users\natea\Desktop\YouTubeFirstCommentBot-master\api.py", line 78, in get_latest_upload
    if time_published >= start_time:
TypeError: '>=' not supported between instances of 'float' and 'str'`

I printed time_published and start_time
`time_published: 1556143358.0
start time is: Sat Mar 28 02:03:52 2020`

Is this not working because I switched to googleapiclient? That's the only answer i could find.

**Comment by jamespeccia** [comment]
The problem is that you cannot compare text and numbers. In order to compare time_published and start_time, they must be the same type. They should be of type float. In order to fix this issue, initialize start_time as,

start_time = time.time()
